---
version: 2
jobs:
  build:
    working_directory: ~/whether_sweater
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: whether_sweater
          RAILS_ENV: test
      - image: postgres:12.4
        environment:
          POSTGRES_USER: whether_sweater
          POSTGRES_DB: whether_sweater_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: whether_sweater-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: whether_sweater-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:{create,schema:load}

      # Run the tests
      - run: bundle exec rspec